apiVersion: v1
kind: Service
metadata:
  name: food-delivery-app-service
spec:
  selector:
    app: food-delivery-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007